// GENERATED FROM WorkoutEngine. Keep this file small: names only.
// Rich metadata/media from Supabase or the free catalogue replaces these
// fallback entries whenever it is available.
//
// Dynamic running names are listed explicitly because several are selected by
// location inside conditional expressions rather than a literal _e('...') call.

const Set<String> offlineProgrammeExerciseNames = <String>{
  'Band Biceps Curl',
  'Band Pull-Apart',
  'Band Romanian Deadlift',
  'Band Row',
  'Banded Squat',
  'Barbell Bench Press',
  'Bird Dog',
  'Bodyweight Squat',
  'Brisk Walk',
  'Bulgarian Split Squat',
  'Cable Lateral Raise',
  'Cable Overhead Extension',
  'Calf Raise',
  'Calf Stretch',
  'Cat-Cow',
  'Chest-Supported Dumbbell Row',
  'Chin-Up',
  'Close-Grip Push-Up',
  'Dead Bug',
  'Diamond Push-Up',
  'Dumbbell Bench Press',
  'Dumbbell Curl',
  'Dumbbell Floor Press',
  'Dumbbell Pullover',
  'Dumbbell Romanian Deadlift',
  'Dumbbell Shoulder Press',
  'Easy Run',
  'Elliptical',
  'EZ-Bar Curl',
  'Face Pull',
  'Fartlek Run',
  'Glute Bridge',
  'Goblet Squat',
  'Hammer Curl',
  'Hamstring Stretch',
  'High Knees',
  'Hip Flexor Stretch',
  'Hip Thrust',
  'Incline Dumbbell Press',
  'Interval Run',
  'Lat Pulldown',
  'Lateral Raise',
  'Leg Curl',
  'Leg Press',
  'Long Easy Run',
  'Machine Chest Press',
  'Machine Shoulder Press',
  'March in Place',
  'Mountain Climber',
  'One-Arm Dumbbell Row',
  'Overhead Triceps Extension',
  'Pike Push-Up',
  'Plank',
  'Plank Shoulder Tap',
  'Prone Y-T Raise',
  'Pull-Up',
  'Push-Up',
  'Recovery Run',
  'Reverse Fly',
  'Reverse Lunge',
  'Romanian Deadlift',
  'Run-Walk Intervals',
  'Seated Cable Row',
  'Seated Calf Raise',
  'Seated Dumbbell Shoulder Press',
  'Seated Leg Curl',
  'Side Plank',
  'Split Squat',
  'Standing Calf Raise',
  'Stationary Bike',
  'Step-Up',
  'T-Bar Row',
  'Tempo Run',
  'Thoracic Rotation',
  'Treadmill Easy Run',
  'Treadmill Intervals',
  'Triceps Pushdown',
  'Warm-Up Walk',
};
