from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text(encoding='utf-8')
    if old not in text:
        raise RuntimeError(f'Patch anchor missing in {path}: {old[:160]}')
    file.write_text(text.replace(old, new, 1), encoding='utf-8')


replace_once(
    'lib/today_dashboard.dart',
    '    await _store.completeSession(activeIndex);\n',
    '    await _store.completeSession(activeIndex, profile: profile);\n',
)

replace_once(
    'lib/today_dashboard.dart',
    '''  Future<void> _startRecoveryDay() async {\n''',
    '''  Future<void> _skipCurrentSession() async {\n    final stored = _stored;\n    final profile = _profile;\n    if (stored == null ||\n        profile == null ||\n        stored.currentSession == null ||\n        stored.activeSessionIndex != null) {\n      return;\n    }\n\n    final index = stored.safeCurrentSessionIndex;\n    final session = stored.programme.sessions[index];\n    final confirmed = await showDialog<bool>(\n      context: context,\n      builder: (context) => AlertDialog(\n        title: const Text('Skip this session?'),\n        content: Text(\n          'LeanIt will record ${session.title} as skipped and use that information when it builds your next training week.',\n        ),\n        actions: [\n          TextButton(\n            onPressed: () => Navigator.pop(context, false),\n            child: const Text('CANCEL'),\n          ),\n          FilledButton(\n            onPressed: () => Navigator.pop(context, true),\n            child: const Text('SKIP SESSION'),\n          ),\n        ],\n      ),\n    );\n    if (confirmed != true) return;\n\n    await _store.skipSession(index, profile: profile);\n    if (mounted) await _load();\n  }\n\n  Future<void> _startRecoveryDay() async {\n''',
)

replace_once(
    'lib/today_dashboard.dart',
    '''                      SizedBox(\n                        width: double.infinity,\n                        child: ElevatedButton.icon(\n                          onPressed: adaptation?.blocksTraining == true\n                              ? null\n                              : _startCurrentWorkout,\n                          icon: Icon(\n                            activeIndex != null\n                                ? Icons.play_circle_fill_rounded\n                                : Icons.play_arrow_rounded,\n                          ),\n                          style: ElevatedButton.styleFrom(\n                            minimumSize: const Size.fromHeight(58),\n                            backgroundColor: const Color(0xFF176B87),\n                            foregroundColor: Colors.white,\n                          ),\n                          label: Text(\n                            adaptation?.blocksTraining == true\n                                ? 'MEDICAL REVIEW BEFORE TRAINING'\n                                : activeIndex != null\n                                    ? 'CONTINUE SESSION'\n                                    : 'START WORKOUT',\n                            style: const TextStyle(fontWeight: FontWeight.w900),\n                          ),\n                        ),\n                      ),\n''',
    '''                      SizedBox(\n                        width: double.infinity,\n                        child: ElevatedButton.icon(\n                          onPressed: adaptation?.blocksTraining == true\n                              ? null\n                              : _startCurrentWorkout,\n                          icon: Icon(\n                            activeIndex != null\n                                ? Icons.play_circle_fill_rounded\n                                : Icons.play_arrow_rounded,\n                          ),\n                          style: ElevatedButton.styleFrom(\n                            minimumSize: const Size.fromHeight(58),\n                            backgroundColor: const Color(0xFF176B87),\n                            foregroundColor: Colors.white,\n                          ),\n                          label: Text(\n                            adaptation?.blocksTraining == true\n                                ? 'MEDICAL REVIEW BEFORE TRAINING'\n                                : activeIndex != null\n                                    ? 'CONTINUE SESSION'\n                                    : 'START WORKOUT',\n                            style: const TextStyle(fontWeight: FontWeight.w900),\n                          ),\n                        ),\n                      ),\n                      if (activeIndex == null) ...[\n                        const SizedBox(height: 10),\n                        SizedBox(\n                          width: double.infinity,\n                          child: OutlinedButton.icon(\n                            onPressed: _skipCurrentSession,\n                            icon: const Icon(Icons.skip_next_rounded),\n                            label: const Text(\n                              'SKIP THIS SESSION',\n                              style: TextStyle(fontWeight: FontWeight.w900),\n                            ),\n                          ),\n                        ),\n                        const SizedBox(height: 5),\n                        const Text(\n                          'Skipping is recorded so LeanIt can adjust next week instead of assuming the plan was completed.',\n                          textAlign: TextAlign.center,\n                          style: TextStyle(\n                            fontSize: 11,\n                            height: 1.35,\n                            color: Color(0xFF829AB1),\n                          ),\n                        ),\n                      ],\n''',
)
